cmake_minimum_required(VERSION 3.5)
project(CPURasterizer)

file(GLOB_RECURSE RASTERIZER_HEADERS "Source/*.hpp")
file(GLOB_RECURSE RASTERIZER_SOURCES "Source/*.cpp")

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIGURATION>")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIGURATION>")

add_subdirectory(Vendored/SDL EXCLUDE_FROM_ALL)

add_executable(CPURasterizer
	${RASTERIZER_HEADERS}
	${RASTERIZER_SOURCES}
)

set_property(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY VS_STARTUP_PROJECT CPURasterizer)

target_include_directories(CPURasterizer PUBLIC
	"${CMAKE_CURRENT_SOURCE_DIR}/Source"
)

target_link_libraries(CPURasterizer 
	PRIVATE SDL3::SDL3
)